### ISSUE TITLE
Can anyone help me with this please?

### ISSUE THREAD

**Issue by rpetersson** [oblitum/Interception#85]
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "C:\python projects local\bot-master\lib\InterceptionWrapper.py", line 161, in __interception_is_keyboard
    return self.interceptionDll.interception_is_keyboard(device)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "C:\python projects local\bot-master\lib\InterceptionWrapper.py", line 161, in __interception_is_keyboard
    return self.interceptionDll.interception_is_keyboard(device)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "C:\python projects local\bot-master\lib\InterceptionWrapper.py", line 161, in __interception_is_keyboard
    return self.interceptionDll.interception_is_keyboard(device)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "C:\python projects local\bot-master\lib\InterceptionWrapper.py", line 161, in __interception_is_keyboard
    return self.interceptionDll.interception_is_keyboard(device)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "C:\python projects local\bot-master\lib\InterceptionWrapper.py", line 161, in __interception_is_keyboard
    return self.interceptionDll.interception_is_keyboard(device)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "C:\python projects local\bot-master\lib\InterceptionWrapper.py", line 161, in __interception_is_keyboard
    return self.interceptionDll.interception_is_keyboard(device)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27.16\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27.16\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\python projects local\bot-master\launcher.py", line 66, in start_auto_py
    auto.start()
  File "C:\python projects local\bot-master\lib\AutoHotPy.py", line 554, in start
    self.interception.interception_set_filter(self.context, self.interception.interception_is_keyboard, InterceptionFilterKeyState.INTERCEPTION_FILTER_KEY_ALL);
  File "C:\python projects local\bot-master\lib\InterceptionWrapper.py", line 210, in interception_set_filter
    return self.interceptionDll.interception_set_filter(context, predicate, filter1)
WindowsError: exception: access violation writing 0x00000007

**Comment by oblitum** [comment]
Sorry but I don't give support for other's people software that make use of this library, you should ask on their forums.
